### ISSUE TITLE
SharedArray improvements

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6#2043]
## initialize SharedArray in non init context

There is nothing preventing us from just letting SharedArray be created outside of the init context, I think it was previous not technically possible as it was using a different mechanism to share the data, but this is no longer a problem.

The only caveat is that it should probably disallow creating SharedArray from `setup`,`teardown` and `handleSummary` as ... well the last 2 aren't all that useful and the first one will not work in a distributed setup (unless we decided that SharedArray should be shared between distributed instances, but I think that will be technically ... very hard :tm: ) 

## SharedArray should be returnable from `setup`

This will need some kind of special finding out that whatever was returned is SharedArray first, and then a way to save this in the JSON and reproduce the array on the other side.

This gets even more complicated due to the fact that you might want to return an array of SharedArrays ... which will mean that this might need to support on many levels :sob: , we might decide to not support this at first.

Because of the caveat mentioned above, it probably will need some ... specific code ?!? 

Alternative: Maybe as suggested in this [comment](https://github.com/k6io/docs/issues/308#issuecomment-849680566) we should just make another breaking change and make the returned setup data always a "SharedObject" or something like that. I would expect that depending on how deep it is "shared" it will either not  save memory, or be slower at least to some degree

## Use cases:

When a lot of data will be generated in `setup`  (for example because of needing to use HTTP request to get the data) and then it will be nice to not get this [data copied for each VU](https://github.com/k6io/docs/issues/308) but instead have it as a single copy. 

Making the SharedArray makeable in the `default` function also can help that as a single VU only will call the initialize code ... once. The problem is that `setup` might still need to do some setupping and there is no way to return this data to `teardown` if it's needed there.

edit: This is likely going to wait for #140 in order to be doable.

**Comment by na--** [comment]
Being able to make a `SharedArray` in VU code would also be very helpful for this use case: https://github.com/k6io/k6/issues/1638#issuecomment-768107236

And I agree returning a SharedArray from `setup()` will be quite hard. I'm not sure if that's what we should do, but if we do it, we should also probably whitelist a few other JS types that currently get mangled because of the JSON encoding and decoding, like `ArrayBuffer`, typed arrays, built-in k6 types, etc. :man_shrugging:

**Comment by na--** [comment]
[This forum topic](https://community.k6.io/t/store-write-data-from-setup-and-read-in-default-main-function/2918/2) is another example where the first part of this issue would have been useful. With the new JS module APIs, implementing that basically boils down to deleting these 3 lines, right? https://github.com/grafana/k6/blob/c4b88f59189705dfa4d97fec0057e202104d5db1/js/modules/k6/data/data.go#L89-L91

If we remove this (now artificial) restriction, everything else should "just work", I think... :thinking:  It should allow users to create a `SharedArray` in one scenario and then use it in another scenario with a later `startTime`. Sort of a delayed init / `setup()` alternative that can make HTTP requests and save the results in a `SharedArray` so they can be used in other scenarios on the same k6 instance. 

There are two potential pitfalls that I can think of:
1. Returning a `SharedArray` in setup will probably currently fail, as mentioned above. The proper solution for this would be properly implementing the second part of the issue above, and I prefer the proposed approach of a `SharedObject`-like implementation. 
    However, if that is too difficult, as the first iteration I think we can simply implement the [`json.Marshaler` interface](https://pkg.go.dev/encoding/json#Marshaler) by the current `SharedArray` object, which should transform `SharedArray` objects returned from `setup()` into normal JS arrays. In the `MarshalJSON` method we can also emit a warning (until we properly implement this) that doing so is probably a bad idea, since it completely negates any benefits from `SharedArray`.
2. A `SharedArray` build during an iteration won't be properly shared among multiple k6 instances (e.g. in a [`k6 cloud`](https://k6.io/docs/cloud/) or a [k6-operator](https://github.com/grafana/k6-operator) test run). I have some ideas of how to properly solve this in the long term, however in the short term we can just emit a warning that explains the problem when a `SharedArray` is created in VU code and the execution segment of the instance is not 100%.

In any case, I think it's worth it to remove the artificial restriction around `SharedArray` usage in VU code. There are certain pitfalls, true, but it will unlock a lot of use cases that are currently not possible to cover by k6...

**Comment by codebien** [comment]
>of a SharedObject-like

Does it mean a k6's wrapped object that supports safe concurrency?

>as the first iteration I think we can simply implement the [json.Marshaler interface](https://pkg.go.dev/encoding/json#Marshaler) by the current SharedArray object

The SharedArray under the hood is a DynamicArray, do we have a way for implementing the interface on it or it would require a wrap? https://github.com/grafana/k6/blob/c4b88f59189705dfa4d97fec0057e202104d5db1/js/modules/k6/data/share.go#L43-L54

Will the `JSON.stringify` function trigger the warning? Would we have a workaround for it? :thinking: 

```js
const data = new SharedArray('some name', function () {
});

export function setup() {
    console.log(JSON.stringify(data)) // I guess it shouldn't emit the warning
}
```

>Making the SharedArray makeable in the default function also can help that as a single VU only will call the initialize code ... once.

It seems a more distributed-friendly solution, if it hasn't critical problems, why not encourage users to use it until we will have a complete working solution for the `setup()` function?

**Comment by na--** [comment]
> Does it mean a k6's wrapped object that supports safe concurrency?
> The SharedArray under the hood is a DynamicArray, do we have a way for implementing the interface on it or it would require a wrap? 

Yes, something like a [`Proxy`](https://pkg.go.dev/github.com/dop251/goja#Proxy) that allows for the dynamic sharing of arbitrary nested data, the bulk of which has only one copy in memory and when parts of it are requested, they are copied on demand to the VU that requested them. Basically, a more powerful version of `SharedArray`.

> Will the JSON.stringify function trigger the warning? Would we have a workaround for it? 

Yes, why not? `JSON.stringify()`-ing the current SharedArrays is also probably a mistake, so no reason not to print a warning :man_shrugging:

**Comment by Perzach** [comment]
Allowing the initialization of SharedArray within the setup context would solve an important use case for my organization. Alternatively we could also solve it if we were allowed to make http requests within the SharedArray function that is run during in the init context.  

Our use case is that we have a large file (~100MB) that we would like to share across many distributed k8s pods running our test. We were hoping to put it on s3 and download it in the test. However we find that we are not allowed to fetch the s3 object within the SharedArray initialization because http requests are not allowed in the init context. Furthermore if we download the s3 object in the setup context, we are unable to initialize a SharedArray because this can only be done in the init context. If we put the file contents in the data block that is returned by the setup function our understanding is that memory usage will grow quickly as we increase number of VUs.

**Comment by guillermotti** [comment]
Hi @Perzach! We had the same problem a few months ago and we found a workaround that maybe will fit for you as well. Let me explain it a bit:

We have a single repository where each team in my company could write their tests scripts. Those scripts and the large files with real data to trigger load tests are generated in a [GitHub Action](https://github.com/empathyco/platform-reusable-github-actions/blob/main/.github/workflows/k6-copy-scripts.yml) and copied to an EFS volume via running a pod. It's a reusable job so you could use it directly from our repo if you have self-hosted runners. And here is the manifest for the pod able to copy script tests and large files to the volume:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: k6-pvc-copy
spec:
  volumes:
    - name: k6-pvc-copy-storage
      persistentVolumeClaim:
        claimName: k6-runner-tests
  containers:
    - name: k6-pvc-copy-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/test"
          name: k6-pvc-copy-storage
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "100m"
          memory: "100Mi"
```

Then the pods running the test can mount the EFS volume and launch the tests using those large files already there in the volume. Here you have an example of what we have (in this case is a template for Argo Workflows but the K6 manifest is the same, you just need to change the `inputs`):

```yaml
apiVersion: k6.io/v1alpha1
          kind: K6
          metadata:
            name: k6-{{`{{inputs.parameters.team}}`}}
          spec:
            parallelism: {{`{{inputs.parameters.parallelism}}`}}
            script:
              volumeClaim:
                name: k6-runner-tests
                file: {{`{{inputs.parameters.team}}`}}/test/{{`{{inputs.parameters.scriptName}}`}}
            arguments: --out prometheus=namespace=k6
            ports:
            - containerPort: 5656
              name: metrics
            runner:
              image: ACCOUNT.dkr.ecr.REGION.amazonaws.com/REPO/IMAGE
              resources:
                requests:
                  cpu: {{`{{inputs.parameters.cpuRequests}}`}}
                  memory: {{`{{inputs.parameters.memoryRequests}}`}}
                limits:
                  cpu: {{`{{inputs.parameters.cpuLimits}}`}}
                  memory: {{`{{inputs.parameters.memoryLimits}}`}}
```

Don't hesitate to ask for more details. Hope it helps!
