### ISSUE TITLE
Grafana shows only "max" value

### ISSUE THREAD

**Issue by Lamera** [grafana/k6#2119]
## Environment

- k6 version: v0.33.0
- OS and version: go1.16.5, linux/amd64
- Docker version: 20.10.8
- InfluxDB image: 1.8
- Grafana image: latest

I modified my docker compose file to make my data last using docker volumes. I decided to make for each project a new database. This can be done directly when running the K6 test:
`k6 run --out influxdb=http://127.0.0.1:8086/mastertest master.js`

## Expected Behavior

All metrics should be pointing to a variable ($DB). So that it works with whatever I define in the K6 run command.

## Actual Behavior

When using the default "k6" database all things are working properly and I get all the metrics in the right place. But as described above I use another name for the database. There must be a hardcoded variable for the database name (k6). In the picture below I used "mastertest" as the name for the database. Then I get only the "max" value for the corresponding metric. The other metrics aren't available.
![image](https://user-images.githubusercontent.com/19840658/130401194-86443e5d-872f-472e-9c85-e2087590fbce.png)

## Steps to Reproduce the Problem

1.docker compose file:
```
version: '3.4'

networks:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - grafana
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_BASIC_ENABLED=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - ./grafana:/etc/grafana/provisioning/
      - grafana-storage:/var/lib/grafana

volumes:
  influxdb:
  grafana-storage:
```
2. `docker-compose up -d`
3. `k6 run --out influxdb=http://127.0.0.1:8086/my_new_db testscript.js`
