### ISSUE TITLE
Progress displayed line by line on Windows 10 (Docker)

### ISSUE THREAD

**Issue by let-aurn** [grafana/k6#2141]
I'm on Windows 10, and instead of displaying a progress bar, it prints the progress line by line.

![image](https://user-images.githubusercontent.com/13006409/134476333-1c649598-da10-4abf-8b6d-4025bc9121f0.png)

Same issue with **CMD** and **Power Shell**

### How to reproduce

```yml
services:
  k6:
    image: loadimpact/k6:latest
    command: run /loadtests/index.js --insecure-skip-tls-verify
    volumes:
      - ./:/loadtests
    environment:
      - LOREM=IPSUM
```

```shell
docker compose up
```

**Comment by imiric** [comment]
Hi there,

this happens when k6 doesn't detect an interactive terminal (TTY), so it falls back to a simpler output. This is typically the case when running in CI environments where you don't need fancy progressbars and such.

Since you're running in Docker, you should enable the pseudo-TTY option (`--tty`) for this to work. You can add `tty: true` to the Docker Compose file.

**Comment by efdknittlfrank** [comment]
`docker-compose` does not run your application with a TTY. Try the following from <https://stackoverflow.com/a/39150040/12391775>:

```yaml
version: "3"
  services:
    k6:
      image: loadimpact/k6:latest
      command: run /loadtests/index.js --insecure-skip-tls-verify
      volumes:
        - ./:/loadtests
      environment:
        - LOREM=IPSUM
      stdin_open: true # docker run -i
      tty: true        # docker run -t ← that's the one
```
