### ISSUE TITLE
`k6 stats` doesn't show metric names since k6 v0.36.0

### ISSUE THREAD

**Issue by na--** [grafana/k6#2420]
`k6 stats` does the equivalent of `curl 'http://localhost:6565/v1/metrics'`. And when running a simple long-running script with the latest k6 master or k6 v0.36.0, if I execute that `curl` command, I'd get a normal result, something like this:
```js
{"data":[{"type":"metrics","id":"vus_max","attributes":{"type":"gauge","contains":"default","tainted":null,"sample":{"value":1}}},{"type":"metrics","id":"default_counter","attributes":{"type":"counter","contains":"default","tainted":true,"sample":{"count":1,"rate":0.006174025497330604}}},{"type":"metrics","id":"vus","attributes":{"type":"gauge","contains":"default","tainted":null,"sample":{"value":1}}}]}
```

However, `k6 stats` will result in this with k6 v0.35.0:
```yaml
- name: vus
  type:
      type: gauge
      valid: true
  contains:
      type: default
      valid: true
  tainted: ""
  sample:
      value: 1
// ...
```

But in something like this with k6 v0.36.0 and beyond:
```yaml
- name: ""
  type:
      type: gauge
      valid: true
  contains:
      type: default
      valid: true
  tainted: ""
  sample:
      value: 1
// ...
```

The `name` is an empty string
