### ISSUE TITLE
Overwriting test-wide tags at key level

### ISSUE THREAD

**Issue by yorugac** [grafana/k6#2694]
### Feature Description

There are two ways to set the [test-wide tags](https://k6.io/docs/using-k6/tags-and-groups/#test-wide-tags): via CLI `--tag` and in script as part of `options` struct. CLI tags fully overwrite the ones in `options` according to the [order of precedence](https://k6.io/docs/using-k6/k6-options/how-to#order-of-precedence).

In case of tags, this is not always desirable behavior, esp. noticeable in CI / CD setups and k6-operator usage: it would be easier to be able to pass CLI tags as an addition to the tags set in the script. E.g. if there is a script:
```
export const options = {
  tags: {
    tag_a: 'foo',
  },
};
...
```
and we run it with `k6 run script.js --tag tag_b=bar`, the output will have only `tag_b` attached. Instead, it'd be good to have both `tag_a` and `tag_b` attached in such a case.

### Suggested Solution (optional)

Tags are essentially a key-value map which means that it can be overwritten not only at it's root but at the key level. E.g. if one passes `tag_a` both in CLI and in the script, then by the order of precedence only CLI value should remain. But if one passes two different tags, they should result in a map with two keys.

**Comment by oleiade** [comment]
After reading your objections @na-- I have a feeling this would lead to somewhat poor UX. That is not to say we shouldn't address this, but we should be wary of what the user interface for that is, and avoid it being too specific to this very case, or too confusing indeed.

Unfortunately, I don't have a better solution to propose at the moment and would lean towards not addressing this if not absolutely necessary as it stands. It might be worth feeding this issue in the croconf project though 😉

**Comment by sniku** [comment]
It is possible to achieve tag merging today with a workaround. 

`k6 run script.js -e MY_EXTRA_TAGS='{"tag_b":"bval"}'`

```js
import http from 'k6/http';

export const options = {
  tags: Object.assign(JSON.parse(__ENV.MY_EXTRA_TAGS), {
    tag_a: 'foo',
  }),
};

export default function mytest() {
  http.get('https://test.k6.io');
}
```

I was going to say that the UX is quite bad, but after writing and running the example, I think it's not too terrible :smile:

**Comment by DaniBencz** [comment]
[snikus' answer](https://github.com/grafana/k6/issues/2694#issuecomment-1263936658) did not work for me, but here is a solution, that did:
https://community.grafana.com/t/test-wide-defined-tags-doesnt-appear-in-influxdb/99112/6

**Comment by oleiade** [comment]
In light of #5714 I realized I didn't have the full picture of this issue, which predates my time on the project. So here is a summary of what's at play, as a refresher 👇🏻

## In the current state of k6

**Assuming a script like this:**

```javascript
export const options = {
  tags: {
    app: "checkout",
    env: "staging",
  },
};
```

**Running:**

`k6 run script.js --tag team=backend`

k6 treats the `--tag` flag as the highest priority and effectively replaces the whole options `tags` object with it:

```javascript
{
  team: "backend"
}
```

## The requested behavior

A common request we hear from users, both internal and external to the project, is that with the same starting options and the same command, the tags should be *merged* across configuration sources, following the priority order k6 already uses (cli > script). We would end up with:

```javascript
{
  app: "checkout",
  env: "staging",
  team: "backend"
}
```

And if the same key is present in both sources (options and cli flag), the higher-priority source wins. So:

```sh
k6 run script.js --tag env=prod
```

**would result in:**

```javascript
{
  app: "checkout",
  env: "prod"
}
```

## Impact & concerns

This is a breaking change, albeit a "small" one. As far as I can tell, the impact is that for users relying on the current (overriding) behavior, the new merging behavior would let unwanted tags through to their metrics/timeseries.

Say you have these options:

```javascript
export const options = {
  tags: {
    app: "checkout",
    owner: "payments",
    env: "dev",
  },
};
```

And you run:

```shell
k6 run script.js --tag env=prod
```

Expecting:

```javascript
{
  env: "prod"
}
```

But after the change you'd instead get:

```javascript
{
  app: "checkout",
  owner: "payments",
  env: "prod"
}
```

That can change dashboards, queries, output results, timeseries cardinality, and so on.

A related side-effect decision, which I think is the smaller problem and fairly easy to solve, is: if we adopt this behavior, how do we also let users *drop* tags they don't want, directly from the command line? For instance, say you have a `debug: true` tag that you don't need in CI or against production because it just adds noise. How do you drop it?

### Mitigation

The main idea Ned floated above at the time was to treat empty-valued tags as a way to drop them:

```sh
k6 run script.js --tag debug=
```

would drop the `debug` tag.

## Solution space

The maintainers agree the proposed behavior is desirable, but acknowledge it would be a **breaking change** with an undefined blast radius across our users' workflows, as well as on other projects built on top of k6 such as [k6-operator](https://github.com/grafana/k6-operator), not to mention the internals of Grafana Cloud k6.

### Potential Path forward

(No decision made as of this writing)

To avoid stalling this any further, or blocking it until v3 (expected May 2027), we're considering to leverage the newly introduced feature-flag support in k6 to roll it out iteratively, starting with #5714. We'd iterate on it, evaluate the changes needed in dependent projects, and aim to make it the mainstream behavior in v3.

We believe this strikes a good balance: addressing our users' needs while minimizing the risk of breaking changes and ensuring a smooth transition for both our users and our own internal projects and products that depend on k6.

### Further context

For larger context, the whole option's management and precedence in k6 is to this day one of the largest pieces of technical debt the project carries, and unfortunately carries through the whole k6 project, ecosystem and infrastructure; and makes it touching non-trivial for us.

**Comment by yordis** [comment]
```yaml
kind: TestRun
spec:
  arguments: >-
    --out opentelemetry
    --tag target=umbrella // footgun if operator assume the script will work by itself and forget this
    --tag env=dev // footgun 
    --tag scenario=myscenario // footgun if operator assume the script will work by itself and forget this
    --tag type=load // footgun if operator assume the script will work by itself and forget this
    -e GRPC_URL=...
    -e TARGET_ENV=dev // footgun if you set it in the tags trying to control with one value inside the script
  parallelism: 1
  runner:
    envFrom:
    - secretRef:
        name: k6-run-config // footgun assume you can set tags based on the env vars from the script
        optional: true
    - secretRef:
        name: k6-shared // footgun assume you can set tags based on the env vars from the script

```


> To avoid stalling this any further, or blocking it until v3 (expected May 2027)

If you will break change and already have a target release, could we add an opt-in based on a new environment variable? We would most likely inject it from a global secret (k6-shared) to enable it. I feel such cost is quite minimal.
