### ISSUE TITLE
Loki log output: Maximum active stream limit exceeded, reduce the number of active streams when 1000s of connection resets received

### ISSUE THREAD

**Issue by stevenebutler** [grafana/k6#2753]
### Brief summary

I'm using Loki to store my log files from test execution and this works well when they are log messages that I generate as the text of my messages is not converted to a label.

However, when K6 generates errors from a huge number of connection resets I start seeing errors from Loki (HTTP 429) with text Maximum active stream limit exceeded, reduce the number of active streams

I'm not sure what's happening as my Loki instance doesn't seem to have recorded any of the connection reset messages. If K6 is logging these kinds of messages as a Loki label value (e.g. for error) it may be exceeding the Loki stream limit.

loki, version 2.6.1 (branch: HEAD, revision: 6bd05c9a4)
  build user:       root@af90ed01061f
  build date:       2022-07-18T08:41:09Z
  go version:       go1.17.6
  platform:         linux/amd64

Using Loki config
```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /var/lib/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
analytics:
  reporting_enabled: false
```

### k6 version

0.40

### OS

Ubuntu Linux 20.04

### Steps to reproduce the problem

1. Run K6 using Loki '--log-output=loki=http://localhost:3100/loki/api/v1/push,label.k6=y'
2. Receive a large number of connection resets during a test when other system malfunctions

### Expected behaviour

Connection reset errors are logged in Loki along with my fail() and throw message/stacktraces that I use to detect logical problems in the test.

### Actual behaviour

Lots of errors logged on the console that error messages couldn't be logged in Loki.
Maximum active stream limit exceeded, reduce the number of active streams
