### ISSUE TITLE
k6 cloud json output of run id to later get status

### ISSUE THREAD

**Issue by damienpontifex** [grafana/k6#2972]
### Feature Description

The use case is being able to start a test run in a CI pipeline, but not wait for execution complete (so as to not block and pay for the pipeline agent). Then at some later time check on the status of the run and pass or fail the stage. 

An example pipeline with Azure DevOps might look like this
```yaml
stages:
- stage: Run
  jobs:
    - job: Run
      steps:
        - script: |
            k6 cloud my-test.js
                --exit-on-running
          env:
            K6_CLOUD_TOKEN: TODO_SUBSTITUTE
          displayName: Schedule load test in k6 cloud
          workingDirectory: $(Pipeline.Workspace)/load-test

# Align this wait time with expected execution time of the k6 run so we don't block an agent to get the results
- stage: WaitForExecution
  jobs:
    - job: WaitForExecution
      pool: server
      steps:
        - task: Delay@1
          inputs:
            delayForMinutes: '30'

- stage: InspectResults
  jobs:
    - job: InspectResults
      steps:
        - script: |
            k6 status .....
          env:
            K6_CLOUD_TOKEN: TODO_SUBSTITUTE
          displayName: Inspect k6 results
```

* Be able to initiate a test run, wait a while, and then get status of that run.
* Today use `--exit-on-running` so the agent initiating the run isn't blocked
* Could use [Read load test run](https://k6.io/docs/cloud/cloud-reference/cloud-rest-api/test-runs/#read-load-test-run) API to get the result, but CLI doesn't give an indication of the run id

### Suggested Solution (optional)

* `k6 cloud my-test.js --exit-on-running --output json` would output something such as `{ "reference_id": 123 }`
* This could then be set as a state in the pipeline so another stage could use this reference
* Either use Cloud REST API to poll state after some delay, or `k6 status` command to enable this from CLI
