### ISSUE TITLE
"k6.io (key for signing binaries) <security@k6.io>" outdated

### ISSUE THREAD

**Issue by gslin** [grafana/k6#2973]
### Brief summary

```
$ curl -s https://dl.k6.io/key.gpg | gpg                       
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096 2021-03-12 [SC]
      C5AD17C747E3415A3642D57D77C6C491D6AC1D69
uid           k6.io (key for signing binaries) <security@k6.io>
sub   rsa4096 2021-03-12 [E]
sub   rsa4096 2021-03-12 [S] [expired: 2023-03-12]
```

### k6 version

N/A

### OS

Ubuntu 20.04 focal

### Docker version and image (if applicable)

N/A

### Steps to reproduce the problem

Run `gpg` to validate key:

```
curl -s https://dl.k6.io/key.gpg | gpg
```

### Expected behaviour

"expired" should be newer.

### Actual behaviour

Expired, 2023-03-12.

**Comment by imiric** [comment]
Hi, thanks for opening this issue.

Apologies for the inconvenience, this one slipped under our radar. :disappointed:

We're looking into it, and will update the key shortly.

**Comment by jtrzebiatowski** [comment]
Hello @imiric ,
Thank you for the update.
Could you precise "shortly"? :)

Hours / Days?

Thanks

**Comment by imiric** [comment]
@jtrzebiatowski This is a high priority issue, so it should be hours. As you can imagine, our current process is not ideal, which is why it might take some time.

In the meantime, you can disable signature verification when installing the package.

- On Ubuntu: pass `--allow-unauthenticated` to `apt-get`. Or if you need to update the repository, set the k6 source in `/etc/apt/sources.list.d/k6.list` to `deb [trusted=yes] https://dl.k6.io/deb stable main`.
- On Fedora/CentOS: pass `--nogpgcheck` to `dnf`.

**Comment by imiric** [comment]
OK, this is fixed now, and the official instructions work again.

Sorry for the inconvenience. We'll discuss this internally and improve our processes to ensure it doesn't happen again.

**Comment by ulidtko** [comment]
Thanks for timely response @imiric :pray: 

Confirming the updated key works for me (without disabling sig-verification).

Amazing how gpg deals with this — AFAICS the deb `Release` files weren't re-signed, yet the older `Release.gpg` verifies just fine with the updated subkey.

**Comment by Nebucatnetzer** [comment]
Could it be that the installation docs aren't up to date yet for this?
https://k6.io/docs/get-started/installation/

**Comment by na--** [comment]
@Nebucatnetzer, the instructions in the docs seem up to date to me, are you still having some issues? 

Please provide some extra information (e.g. what your OS is, what command you are running, what error you are getting, etc.) so we can diagnose the problem and help you.

**Comment by Nebucatnetzer** [comment]
Thank you for the quick reply, I will be on vacation for two weeks. 
I will respond afterwards with more details 👍

**Comment by Nebucatnetzer** [comment]
Please excuse the strange reply before, I didn't expect some answering this quickly and thought that you might reply during my vacation.

It probably was a problem with the `apt_key` module from Ansible.
For some reason it didn't pull the updated key and therefore `apt update` always failed.
I removed the key manually and used the "new" method to the deploy  the key, now it is working.

This was with Ubuntu 22.04.

```
- name: One way to avoid apt_key once it is removed from your distro
  block:
    - name: somerepo |no apt key
      ansible.builtin.get_url:
        url: https://download.example.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/somerepo.asc

    - name: somerepo | apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/myrepo.asc] https://download.example.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
```
