### ISSUE TITLE
K6 can connect with socket.io ?

### ISSUE THREAD

**Issue by exodia0x** [grafana/k6#3097]
Now I just use Artillery for load test with uri socket.io server i want to change it for k6. How do we do? I use Websocket and ws (import ws from 'k6/ws') module connect with wss:// it not working and connect to to server

Example Code in artillery

```
config:
  target: "https://MyDomainName"
  phases:
    - duration: 1
      arrivalRate: 1
      # rampTo: 100
      name: "Ramp-up to 100 Users for 5 minutes"
    # - duration: 3600
    #   arrivalRate: 100
    #   name: "Endurance 100 Users for 1 hour"
    # - duration: 300
    #   arrivalRate: 0
    #   name: "Drop to 0 Users for 5 minutes"
  engines:
   socketio-v3:
    extraHeaders: 
      key: "Testing Load"
    transports: ["websocket"]

scenarios:
  - name: " > Send Message and Check Respond == ACT scenario"
    engine: socketio-v3
    flow:
      - think: 1
      - emit:
          channel: "command"
          event: "command"
          data:
            key: 'Testing Load'
            command: 'Testing Load_SinkTOME'
            value:
              msg: 'Testing Form Artillery'
              modifyDate: '{{ value.modifyDate }}'
        acknowledge:
          match:
            json: "$.result"
            value: "act"
      - think: 1
```

Did anyone can guide or some example code likes my code
Thank you
