### ISSUE TITLE
K6 is support loadtesting with socket.io v3-v4 ?

### ISSUE THREAD

**Issue by exodia0x** [grafana/k6#3230]
Did K6 can running loadtesting socket.io v3 or v4 ? I try to running but it's connect to app and handshake still got status 101. I using other tools but is good for k6 is supported. Or any way to using?

Example code in artillery.

```
config:
  target: "https://mydomainwithsocket.io"
  processor: "random.js"

  phases:
    - duration: 300
      arrivalRate: 200
      name: "200 Users for 5 minutes"

  engines:
   socketio-v3:
    transports: ["websocket"]


scenarios:
  - name: "Emit an event Message Command"
    engine: socketio-v3
    flow:
      - emit:
          channel: "command"
          data:
            protocol:
              version: "1"
              command: "message"
              subCommand: ""
              qos: "normal"
              topic: "MyTopic.1"
              token: "a12344444123RKASF"
              service: "TEST"
              diagMessage: ""
            header:
              version: "1.0"
              timestamp: "2023-05-04T14:51:06.157Z"
              identity:
                device: "123444"
              tmfSpec: "22222222"
            body: {}
        response:
          on: event
          match:
            - json: "$.protocol"
              value: "OK"
```
