### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by schurmann** [grafana/k6#3269]
### Brief summary

I'm evaluating K6 as a load testing framework and it looks really promising. However, the high memory usage is one of the things holding me back when running a `soak test`. The memory usage is almost monotonically increasing during the test and will eventually be too much. I'm following the [recommendations](https://github.com/grafana/k6/issues/2367#issuecomment-1028866630) with no `--no-summary --no-thresholds` and using prometheus as an `--out` sink.

### k6 version

0.45

### OS

Amazon Linux (EKS)

### Docker version and image (if applicable)

grafana/k6:0.45.0

### Steps to reproduce the problem

K6 parameters:

```yaml
spec:
  containers:
  - args:
    - run
    - --no-summary
    - --no-thresholds
    - --config
    - /k6-scripts/config.json
    - --out
    - experimental-prometheus-rw
    - /k6-scripts/test.js
    env:
    - name: K6_PROMETHEUS_RW_SERVER_URL
      value: <URL>
    - name: K6_PROMETHEUS_RW_TREND_STATS
      value: p(50),p(95),p(99)
    - name: K6_PROMETHEUS_RW_PUSH_INTERVAL
      value: 1m
```

```js
export default function (data) {
    const options = {
        headers: {
            Authorization: data.authorization
        },
    };
    const res = http.get(target, options);
    check(res, {
        'protocol is HTTP/2': (r) => r.proto === 'HTTP/2.0',
        'status is 200': (r) => r.status === 200,
    });
}
```

```json
{
    "discardResponseBodies": true,
    "scenarios": {
        "constant_request_rate": {
            "executor": "constant-arrival-rate",
            "rate": 4000,
            "timeUnit": "1s",
            "duration": "48h",
            "preAllocatedVUs": 150
        }
    },
    "thresholds": {
        "http_req_duration{scenario:constant_request_rate}": [
            {
                "threshold": "p(99)<1000",
                "abortOnFail": true
            }
        ],
        "checks{check:status is 200}": [
            {
                "threshold": "rate>=0.99",
                "abortOnFail": false
            }
        ]
    }
}

```

### Expected behaviour

I expect the memory to not keep increasing since the metrics should be flushed every minute.

### Actual behaviour

![image](https://github.com/grafana/k6/assets/8396695/9482811d-e321-49f0-83d5-0bb9df8af124)
