### ISSUE TITLE
Unable to access environment variables referenced in `docker-compose.yml`

### ISSUE THREAD

**Issue by wujekbogdan** [grafana/k6#3827]
### Brief summary

I can't access `__ENV.VARIABLE_NAME` variables which are referenced in `docker-compose.yml` the following way:

``` yml
services:
  k6:
    image: grafana/k6:0.52.0
    volumes:
      - ./dist:/scripts
    command: run /scripts/index.js
    environment:
      SERVER_URL: ${SERVER_URL} # referenced variables don't work
```

I can only access variables that are hardcoded in `docker-compose.yml` the following way:

``` yml
services:
  k6:
    image: grafana/k6:0.52.0
    volumes:
      - ./dist:/scripts
    command: run /scripts/index.js
    environment:
      SERVER_URL: https://my.server.com # hardcoded variable work fine
```

In both cases `docker-compose config` results in:

``` yml
→ docker-compose config
name: load-tester
services:
  k6:
    command:
      - run
      - /scripts/index.js
    environment:
      SERVER_URL: https://my.server.com
```

### k6 version

0.52.0

### OS

macOS 14.5

### Docker version and image (if applicable)

25.0.0, build e758fe5a7f

### Steps to reproduce the problem

Devine an environment variable on the host machine

``` sh
export SERVER_URL=https://my.server.com
```

Set up k6 with docker-compose and reference the environment variable:

``` yml
services:
  k6:
    image: grafana/k6:0.52.0
    volumes:
      - ./dist:/scripts
    command: run /scripts/index.js
    environment:
      SERVER_URL: ${SERVER_URL}
```

Define a script that prints out the variable:

``` ts
// index.ts
export default async () => {
  console.log('SERVER_URL', __ENV.SERVER_URL);
};
```

Verify if the variable is set by running

``` yml
docker-compose config
```

Which should result in:

``` yml
services:
  k6:
    image: grafana/k6:0.52.0
    volumes:
      - ./dist:/scripts
    command: run /scripts/index.js
    environment:
      SERVER_URL: https://my.server.com # hardcoded variable work fine
```

Run the container with `docker compose up`

### Expected behaviour

Should print out the variable

``` sh
k6-1  | time="2024-07-03T15:14:21Z" level=info msg="SERVER_URL https://my.server.com" source=console
```

### Actual behaviour

Prints out the following as if the variable wasn't set.

``` sh
k6-1  | time="2024-07-03T15:14:21Z" level=info msg="SERVER_URL " source=console
```

---
I can verify if the variable is set by running:

``` sh
docker exec -it my_container_name /bin/sh
echo $SERVER_URL
```

And it properly prints out the expected value.

**Comment by aukevanleeuwen** [comment]
@wujekbogdan : I have no official role here in this project, I just happened to come across this issue and it intrigued me, so I tried to reproduce:

```
❯ cat docker-compose.yml
services:
  k6:
    image: grafana/k6:0.52.0
    volumes:
      - ./:/scripts
    command: run /scripts/script.js
    environment:
      SERVER_URL: ${SERVER_URL}
```

```
❯ cat script.js
export default function () {
    console.log('Server URL: ' + __ENV.SERVER_URL);
}
```

```
❯ export SERVER_URL=https://example.com/foo

❯ docker compose up
[+] Running 1/0
 ✔ Container k6-test-k6-1  Created                                                                                                                 0.0s
Attaching to k6-1
k6-1  |
k6-1  |           /\      |‾‾| /‾‾/   /‾‾/
k6-1  |      /\  /  \     |  |/  /   /  /
k6-1  |     /  \/    \    |     (   /   ‾‾\
k6-1  |    /          \   |  |\  \ |  (‾)  |
k6-1  |   / __________ \  |__| \__\ \_____/ .io
k6-1  |
k6-1  |      execution: local
k6-1  |         script: /scripts/script.js
k6-1  |         output: -
k6-1  |
k6-1  |      scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
k6-1  |               * default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)
k6-1  |
k6-1  | time="2024-07-04T07:25:14Z" level=info msg="Server URL: https://example.com/foo" source=console
k6-1  |
k6-1  |      data_received........: 0 B 0 B/s
k6-1  |      data_sent............: 0 B 0 B/s
k6-1  |      iteration_duration...: avg=92.37µs min=92.37µs med=92.37µs max=92.37µs p(90)=92.37µs p(95)=92.37µs
k6-1  |      iterations...........: 1   5644.392014/s
k6-1  |
k6-1  |
k6-1  | running (00m00.0s), 0/1 VUs, 1 complete and 0 interrupted iterations
k6-1  | default ✓ [ 100% ] 1 VUs  00m00.0s/10m0s  1/1 iters, 1 per VU
k6-1 exited with code 0
```

So seems to print it correctly?
