### ISSUE TITLE
how to use K6_WEB_DASHBOARD in operator mode?

### ISSUE THREAD

**Issue by CoffeeHi** [grafana/k6#3980]
Hi guys, I deploy k6 operator in k8s cluster, but I don't know how to show K6_WEB_DASHBOARD when running TestRun CR, is it possible to show  K6_WEB_DASHBOARD in distributed mode k6?
 I have tried in TestRun CR, but does not work.
```
  runner:
    env:
      - name: K6_WEB_DASHBOARD
        value: "true"
      - name: K6_WEB_DASHBOARD_PORT
        value: "5665"
      - name: K6_WEB_DASHBOARD_OPEN
        value: "true"
```
