### ISSUE TITLE
The 'browser_http_req_failed' metric is not exported to Prometheus.

### ISSUE THREAD

**Issue by Hongwei999** [grafana/k6#4327]
### Brief summary

After launching any k6-browser script using the following container:

`- name: k6
          image: grafana/k6:0.50.0-with-browser
          resources:
            limits:
              memory: '13000Mi'
            requests:
              cpu: '500m'
              memory: '13000Mi'
          securityContext:
            runAsUser: 0
          command: [ "sh", "-c" ]
          args:
            - |
              k6 run ./${ parameters.file_name } --out experimental-prometheus-rw --tag testid=${ test_tag } --tag tipoPdr=${ tipo_Pdr } --tag name_app=${ name }
              exit 0
          workingDir: /temp-repo-pdr/k6/
          env:
            - name: K6_PROMETHEUS_RW_SERVER_URL
              value: 'http://myPrometheus/api/v1/write'
            - name: K6_PROMETHEUS_RW_TREND_STATS
              value: p(90),p(95),p(99),min,max,avg,count
            - name: K6_PROMETHEUS_RW_PUSH_INTERVAL
              value: '10000'
          volumeMounts:
            - name: clone-dependencies-pdr
              mountPath: /temp-repo-pdr  ` 

all metrics are exported except for 'browser_http_req_failed'. The only similar metric is 'browser_http_req_failed_rate' but that one is not useful to me, as I would need to know the total number of calls made.

### xk6-browser version

0.50.0-with-browser

### OS

Linux/amd64

### Chrome version

125.0.6422.112-r0

### Steps to reproduce the problem

This happens with any script executed with the variable:
```yaml
          args:
            - |
              k6 run ./${ parameters.file_name } --out experimental-prometheus-rw --tag testid=${ test_tag } --tag tipoPdr=${ tipo_Pdr } --tag name_app=${ name }
              exit 0
          workingDir: /temp-repo-pdr/k6/
          env:
            - name: K6_PROMETHEUS_RW_SERVER_URL
              value: 'http://prometheus-k6.pruebascarga.svc.cluster.local:9090/api/v1/write'
            - name: K6_PROMETHEUS_RW_TREND_STATS
              value: p(90),p(95),p(99),min,max,avg,count
            - name: K6_PROMETHEUS_RW_PUSH_INTERVAL
              value: '10000'
```

### Expected behaviour

Metric 'browser_http_req_failed' exported to Prometheus

### Actual behaviour

![image](https://github.com/grafana/k6/assets/55995823/1ccbc727-3a79-4a0f-9b2d-bc7252288f98)

There is not the 'browser_http_req_failed' metric
