### ISSUE TITLE
k6-browser Docker image not working in non-privileged environments

### ISSUE THREAD

**Issue by tao-aleixandre** [grafana/k6#4597]
### Brief summary

The current official Docker image ([grafana/k6:0.57.0-with-browser](https://hub.docker.com/layers/grafana/k6/0.57.0-with-browser/images/sha256-c2a73e0817f98788a8002cc13a95dcf2890cd170388655a30c0c3c1cac85fb07)) requires privileged capabilities (root access or seccomp adjustments) to properly launch Chromium. (`SYS_ADMIN` capability or root similar)

### k6 version

v0.57.0

### OS

Alpine

### Docker version and image (if applicable)

grafana/k6:0.57.0-with-browser

### Steps to reproduce the problem

Steps to Reproduce the Problem

1. **Create a Kubernetes Pod in a restricted namespace:**
   - The namespace has **Pod Security Admission (PSA)** or **OPA Gatekeeper policies applied**.
   - Example restrictions:
     - `privileged: false`
     - `allowPrivilegeEscalation: false`
     - `readOnlyRootFilesystem: true`
     - `seccompProfile: RuntimeDefault`
     - `runAsNonRoot: true`

2. **Deploy a Pod using the official Docker image:**
   - Image: `grafana/k6:0.57.0-with-browser`
   - Command: 
     ```sh
     k6 run /path/to/browser-test.js
     ```

3. **Run a basic browser test (xk6-browser) in the pod:**
   - The test uses `browser.newPage()`, navigates to a URL, performs login steps, and takes screenshots.

4. **Observe the error when Chromium launches:**
   - Error message:
     ```
     process with PID xx unexpectedly ended: signal: trace/breakpoint trap (core dumped)
     error building browser on IterStart: launching browser: browser process ended unexpectedly
     ```
   - This happens immediately after calling:
     ```javascript
     const page = await browser.newPage();


### Expected behaviour

The k6-browser container should be able to run in restricted kubernetes environments:
    - Run as a **non-root user**.
    - Not require `CAP_SYS_ADMIN`

### Actual behaviour

- The `k6-browser` Docker image fails to run in Kubernetes environments where containers are restricted from running as root or with elevated privileges. Error shows that Chromium crashes in the middle of the execution.

**Comment by zgastley** [comment]
Facing the same exact issue. Thank you for opening this!

**Comment by nadiamoe** [comment]
Hey @tao-aleixandre, happy to try and help you here.

I haven't been able to reproduce your problem with the setup I'm pasting below, so there might be some differences between what I'm trying based on your message and your environment. It would be helpful if you could:
- Post the exact pod manifest you're running, after any mutation done by webhooks (if any)
- The OS, kernel, and container runtime (CRI) that your nodes are using
- The concrete k6 script you're trying to run

With that we should hopefully be able to reproduce the problem and try to figure out what exactly is causing that error 😄 

```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: k6-repro
  name: k6-browser-repro
spec:
  containers:
    - name: k6
      image: grafana/k6:0.57.0-with-browser
      securityContext:
        runAsNonRoot: true
        runAsUser: 12345 # cri-o requires a numeric UID
        privileged: false
        allowPrivilegeEscalation: false
      env:
        - name: K6_BROWSER_ARGS
          value: "--verbose"
      command:
        - k6
      args:
        - run
        - /script/script.js
      volumeMounts:
        - name: script
          mountPath: /script/script.js
          subPath: script.js
  volumes:
    - name: script
      configMap:
        name: script
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: k6-repro
  name: script
data:
  script.js: |-
    import { browser } from 'k6/browser';
    import { check } from 'https://jslib.k6.io/k6-utils/1.5.0/index.js';

    export const options = {
      scenarios: {
        ui: {
          executor: 'shared-iterations',
          options: {
            browser: {
              type: 'chromium',
            },
          },
        },
      },
      thresholds: {
        checks: ['rate==1.0'],
      },
    };

    export default async function () {
      const context = await browser.newContext();
      const page = await context.newPage();

      try {
        await page.goto('https://test.k6.io/my_messages.php');

        await page.locator('input[name="login"]').type('admin');
        await page.locator('input[name="password"]').type('123');

        await Promise.all([page.waitForNavigation(), page.locator('input[type="submit"]').click()]);

        await check(page.locator('h2'), {
          header: async (h2) => (await h2.textContent()) == 'Welcome, admin!',
        });
      } finally {
        await page.close();
      }
    }
```
