### ISSUE TITLE
Network metrics missing from results sent to opentelemetry backend

### ISSUE THREAD

**Issue by seanankenbruck** [grafana/k6#4719]
### Brief summary

I've enabled k6 to push test run metrics to an opentelemetry collector as described in the docs [here](https://grafana.com/docs/k6/latest/results-output/real-time/opentelemetry/). The integration works and some metrics are being sent. I can retrieve them from my metrics datasource (i.e. http metrics, vus, checks total, etc.), but all metrics of type `Counter` are omitted from the results. This includes Network metrics `data_received` and `data_sent` as well as Execution metrics like `iterations`. 

Since these metrics are considered [built-in metrics](https://grafana.com/docs/k6/latest/using-k6/metrics/reference/#standard-built-in-metrics), I would expect them to be sent by default to the collector when streaming has been enabled. However, that is not the case. They show up in the stdout log output from the k6 test run, but not when I query them in my mimir backend. 

Here is a snippet of my configuration of a k6-operator TestRun object which is where I have to enable this to inject the environment variables into the k6 test when it runs:

```yaml
...
arguments: "--out experimental-opentelemetry"
...
runner:
  env:
    - name: K6_OTEL_EXPORTER_TYPE
        value: "http"
      - name: K6_OTEL_HTTP_EXPORTER_INSECURE
        value: "true"
      - name: K6_OTEL_HTTP_EXPORTER_ENDPOINT
        value: "otlp-collector.{{ .Values.namespace }}.svc.cluster.local:4318"
      - name: K6_OTEL_HTTP_EXPORTER_URL_PATH
        value: /v1/metrics
      - name: K6_OTEL_HEADERS
        value: "X-Scope-OrgId=tenant-1"
      - name: K6_OTEL_METRIC_PREFIX
        value: "k6_"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "service_name=k6-otlp-test,environment={{ .Values.namespace }},test_name=otlp-metrics-integration"
```

Are these _Network_ and _Execution_ metrics not currently supported? Is there a limitation on _Counter_ metrics or is there a way to enable them and ensure all metrics are sent to my collector for reporting purposes?  

### k6 version

k6 v1.0.0-rc1

### OS

linux/amd64

### Steps to reproduce the problem

Create a k6 test using the instructions for running inside a k8s cluster with the k6-operator
Add the experimental opentelemetry argument to stream metrics to an otel collector
Run the test

### Expected behaviour

All metrics shown in the test summary logs are sent to the collector

### Actual behaviour

Some metrics are missing, including all metrics of type `Counter`
