### ISSUE TITLE
HAR converter batches dependent requests

### ISSUE THREAD

**Issue by thorstenkampe** [grafana/k6#808]
I recorded a web browser session to http://www.microsoft.com, saved the session as HAR file and converted the file to JavaScript for replaying. A look into the generated code shows that the recording and the conversion worked well (see below): I open http://www.microsoft.com/ and I'm redirected to https://www.microsoft.com/de-de/

But the HTTP debug output shows the requests out of order - first "GET /de-de/", then "GET /".
Obviously that would make any real debugging via ``http-debug` impossible.
```
          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/ .io

  execution: local-
     output: -
     script: .\session.js

    duration: -,  iterations: 1
         vus: 1, max: 1

Request: [----------------------------------------------------------] starting
GET /de-de/ HTTP/1.1
Host: www.microsoft.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en
Connection: keep-alive
Upgrade-Insecure-Requests: 1

Request:
GET / HTTP/1.1
Host: www.microsoft.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en
Connection: keep-alive
Upgrade-Insecure-Requests: 1

RedirectResponse:
HTTP/1.1 302 Moved Temporarily
Connection: keep-alive
Date: Sun, 14 Oct 2018 08:50:14 GMT
Location: https://www.microsoft.com/de-de/
X-Rtag: ARRPrd
Content-Length: 0
```
```
import { group, sleep } from 'k6';
import http from 'k6/http';

// Version: 1.1
// Creator: Firefox
// Browser: Firefox

export let options = {
    maxRedirects: 0,
};

export default function() {

    group("page_1 - Neuer Tab", function() {
        let req, res;
        req = [{
            "method": "get",
            "url": "http://www.microsoft.com/",
            "params": {
                "headers": {
                    "Host": "www.microsoft.com",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                    "Accept-Language": "en",
                    "Accept-Encoding": "gzip, deflate",
                    "Connection": "keep-alive",
                    "Upgrade-Insecure-Requests": "1"
                }
            }
        },{
            "method": "get",
            "url": "https://www.microsoft.com/de-de/",
            "params": {
                "headers": {
                    "Host": "www.microsoft.com",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                    "Accept-Language": "en",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Connection": "keep-alive",
                    "Upgrade-Insecure-Requests": "1"
                }
            }
        }];
```
